# Generated by Django 4.1.3 on 2023-01-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bbs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="user_name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
